In [1]:
import pandas as pd
import random

random.seed(42)

# Define data parameters
regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

# Generate 200 sales transactions
data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)
print(df.head(10))
print(f"\nDataset shape: {df.shape}")

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

In [3]:
#Task 1: Basic Grouping and Single Aggregations

#Perform the following grouping operations:

    #Calculate total sales amount for each region using groupby() and sum()
    #Group by region and calculate sum of sales_amount

region_sales = df.groupby('region')['sales_amount'].sum().reset_index()

print("\nTotal Sales by Region:")
print(region_sales)

Total Sales by Region:
  region  sales_amount
0   East      95189.81
1  North     135181.16
2  South     158977.36
3   West     109383.07

df.groupby('region'): This groups the DataFrame df by the unique values in the region column. This means all rows with the same region will be grouped together.
['sales_amount'].sum(): After grouping, it selects the sales_amount column and then calculates the sum of sales_amount for each group (i.e., for each region).

In [4]:
#Sort Regions by Highest Sales
region_sales_sorted = region_sales.sort_values(by='sales_amount', ascending=False)

print("\nTop Performing Regions:")
print(region_sales_sorted)

Top Performing Regions:
  region  sales_amount
2  South     158977.36
1  North     135181.16
3   West     109383.07
0   East      95189.81



Certainly! This code sorts the region_sales DataFrame, which we previously created, to identify the top-performing regions. Here's how it works:

    region_sales.sort_values(by='sales_amount', ascending=False): This line sorts the region_sales DataFrame.
        by='sales_amount': Specifies that the sorting should be based on the values in the sales_amount column.
        ascending=False: Indicates that the sorting should be in descending order, meaning the regions with the highest sales will appear at the top.

In [5]:
#Count Number of Transactions for Each Category
category_transactions = df.groupby('category')['transaction_id'].count().reset_index()

print("\nTransactions per Category:")
print(category_transactions)

Transactions per Category:
        category  transaction_id
0          Books              39
1       Clothing              42
2    Electronics              45
3  Home & Garden              43
4         Sports              31

df.groupby('category'): This groups the DataFrame df based on the unique values in the category column. All rows belonging to the same category are grouped together.
['transaction_id'].count(): After grouping, it selects the transaction_id column. The .count() method then tallies the number of non-null transaction IDs within each category group

In [6]:
#Average Sales Amount per Salesperson
avg_salesperson_sales = df.groupby('salesperson')['sales_amount'].mean().reset_index()

print("\nAverage Sales per Salesperson:")
print(avg_salesperson_sales)

Average Sales per Salesperson:
  salesperson  sales_amount
0       Alice   1998.432273
1         Bob   2554.919063
2       Carol   2454.368571
3       David   2743.036444
4        Emma   2493.457273
5       Frank   2464.135750

for each salesperson in your df DataFrame. Let's break it down:

    df.groupby('salesperson'): This groups the DataFrame df by the unique values in the salesperson column. All rows that have the same salesperson will be grouped together.
    ['sales_amount'].mean(): After grouping, it selects the sales_amount column and then calculates the average (mean) of sales_amount for each group (i.e., for each salesperson).
    .reset_index(): By default, the salesperson would become the index of the resulting Series.

groupby() → Split data into groups

sum() → Total sales

count() → Number of transactions

mean() → Average sales

reset_index() → Convert grouped result to DataFrame

sort_values() → Identify top performers

In [7]:
#Task 2: Multi-Column Grouping and Multiple Aggregations
#Total Sales for Each Region and Category Combination

#Group by region and category together and calculate the total sales amount.

region_category_sales = df.groupby(['region', 'category'])['sales_amount'].sum().reset_index()

print("\nTotal Sales by Region and Category:")
print(region_category_sales)

Total Sales by Region and Category:
   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22


    df.groupby(['region', 'category']): This is a multi-column grouping. It groups the DataFrame df based on the unique pairs of values found in both the region and category columns. All rows that share the same region and category will be grouped together.
    ['sales_amount'].sum(): After the data has been grouped by both region and category, this part selects the sales_amount column and then calculates the sum of sales_amount for each of those unique region-category groups. This gives you the total sales for each specific region-category combination.
    .reset_index(): Similar to previous examples, after groupby() and sum(), region and category would become the multi-level index of the resulting Series. reset_index() converts these indices back into regular columns in the DataFrame, making it easier to read and use.

The final two lines print a descriptive header and then display the region_category_sales DataFrame, showing the total sales for each region and category combination.

In [8]:
#Multiple Metrics for Each Salesperson
#Calculate three metrics at once using .agg().
salesperson_performance = df.groupby('salesperson')['sales_amount'].agg(['sum', 'mean', 'count']).reset_index()

print("\nSalesperson Performance Metrics:")
print(salesperson_performance)

Salesperson Performance Metrics:
  salesperson        sum         mean  count
0       Alice   43965.51  1998.432273     22
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
3       David  123436.64  2743.036444     45
4        Emma   82284.09  2493.457273     33
5       Frank   98565.43  2464.135750     40

df.groupby('salesperson'): This groups the DataFrame df by the unique values in the salesperson column. All rows belonging to the same salesperson are grouped together.
['sales_amount']: After grouping, we select the sales_amount column because that's the column we want to perform aggregations on.
.agg(['sum', 'mean', 'count']): This is where multiple aggregations happen. The .agg() method allows you to apply several aggregation

In [10]:
#Identify the Top Salesperson

#Sort by total sales in descending order.
top_salespersons = salesperson_performance.sort_values(by='sum', ascending=False)

print("\nSalespersons Ranked by Total Sales:")
print(top_salespersons)

Salespersons Ranked by Total Sales:
  salesperson        sum         mean  count
3       David  123436.64  2743.036444     45
5       Frank   98565.43  2464.135750     40
4        Emma   82284.09  2493.457273     33
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
0       Alice   43965.51  1998.432273     22

The final two lines print a descriptive header and then display the top_salespersons DataFrame, showing the salespersons ranked from highest to lowest total sales.

In [13]:
#Find the Category With Maximum Total Revenue

#First calculate total revenue per category, then use .idxmax().
category_sales = df.groupby('category')['sales_amount'].sum()

top_category = category_sales.idxmax()

print("\nTotal Sales by Category:")
print(category_sales)

print("\nCategory with Highest Revenue:")
print(top_category)

Total Sales by Category:
category
Books            103987.15
Clothing         106312.43
Electronics      114464.29
Home & Garden     90954.92
Sports            83012.61
Name: sales_amount, dtype: float64

Category with Highest Revenue:
Electronics

category_sales = df.groupby('category')['sales_amount'].sum()

top_category = category_sales.idxmax()

print("\nTotal Sales by Category:")
print(category_sales)

print("\nCategory with Highest Revenue:")
print(top_category)

In [23]:
#Task 3: Custom Aggregation and Complete Sales Report
#Define a Custom Aggregation Function
def sales_range(x):
    return x.max() - x.min()
    print('custom aggregation created:')

Create a function to calculate the sales range (difference between maximum and minimum sales).
x represents the grouped column values.

x.max() → highest transaction value

x.min() → lowest transaction value

Range = max − min

In [25]:
#Apply Custom and Standard Aggregations
region_analysis = df.groupby('region')['sales_amount'].agg(
    ['sum', 'mean', 'min', 'max', sales_range]
).reset_index()

print("\nRegional Sales Analysis:")
print(region_analysis)

Regional Sales Analysis:
  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

group the dataset by region and apply multiple aggregations including the custom function.
sum → total revenue per region

mean → average transaction value

min / max → lowest and highest sale

sales_range → spread of transaction values

In [26]:
#Create the Final Sales Summary Report

#Now generate a manager-friendly summary report.

final_report = df.groupby('region').agg({
    'sales_amount': ['sum', 'mean'],
    'customer_id': 'count'
}).reset_index()

print("\nFinal Regional Sales Summary:")
print(final_report)

Final Regional Sales Summary:
  region sales_amount              customer_id
                  sum         mean       count
0   East     95189.81  2213.716512          43
1  North    135181.16  2413.949286          56
2  South    158977.36  2789.076491          57
3   West    109383.07  2485.978864          44

df.groupby('region'): This groups the DataFrame df by the unique values in the region column. All transactions from the same region are grouped together.
.agg({ 'sales_amount': ['sum', 'mean'], 'customer_id': 'count' }): This is a powerful way to apply different aggregation functions to different columns simultaneously:

    For the sales_amount column, it calculates both the 'sum' (total sales) and the 'mean' (average sales) for each region.
    For the customer_id column, it calculates the 'count'. In this context, using count on customer_id after grouping by region effectively counts the number of transactions (or rows) within each region, assuming customer_id is always present for a transaction.

.reset_index(): After the aggregations, 'region' would become the index. reset_index() converts 'region' back into a regular column, making the output a cleaner DataFrame.

In [29]:
#Understanding Multi-Level Column Structure
#sales_amount =sum
#sales_amount = mean
#customer_id = count
#one column has multiple aggregations applied.

 This cell is a descriptive text rather than executable code. It explains the multi-level column structure you would observe in the output of the previous final_report DataFrame, which was generated using groupby() and agg().

When you use .agg() with a dictionary to apply different functions to different columns

In [30]:
#Difference from Single Aggregations
df.groupby('region')['sales_amount'].sum()

region
East      95189.81
North    135181.16
South    158977.36
West     109383.07
Name: sales_amount, dtype: float64



    df.groupby('region'): This groups the DataFrame df by the unique values in the region column. This means all rows with the same region will be grouped together.
    ['sales_amount']: After grouping, it selects the sales_amount column, indicating that the aggregation will be performed on this specific column.
    .sum(): This is the aggregation function applied. It calculates the sum of all sales_amount values within each region group.

The result will be a Pandas Series where the index is the region and the values are the total sales_amount for that region. This is shown in the output below the code cell.

In [33]:
#Multiple Aggregations (Dictionary)
df.groupby('region').agg({
    'sales_amount':['sum','mean'],
    'customer_id':'count'
})

       sales_amount              customer_id
                sum         mean       count
region
East       95189.81  2213.716512          43
North     135181.16  2413.949286          56
South     158977.36  2789.076491          57
West      109383.07  2485.978864          44

    different columns simultaneously:
        For the sales_amount column, it calculates both the 'sum' (total sales) and the 'mean' (average sales) for each region.
        For the customer_id column, it calculates the 'count'. In this context, using count on customer_id after grouping by region effectively counts the number of transactions (or rows) within each region, assuming customer_id is always present for a transaction.

The output of this operation will be a DataFrame with a multi-level column index.

In [34]:
#clean report
final_report.columns = ['region', 'total_sales', 'avg_sales', 'transactions']

print(final_report)

  region  total_sales    avg_sales  transactions
0   East     95189.81  2213.716512            43
1  North    135181.16  2413.949286            56
2  South    158977.36  2789.076491            57
3   West    109383.07  2485.978864            44

displays the final_report DataFrame with its newly assigned, more descriptive column names. This results in a 'cleaner' report, as indicated by the comment #clean report, making it much easier for a manager or analyst to understand at a glance.